//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicFacebookFeatures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicFacebookFeatures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap batman {
            get {
                object obj = ResourceManager.GetObject("batman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Events&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;Summer Beach Party&quot;,
        ///      &quot;HostName&quot;: &quot;John Doe&quot;,
        ///      &quot;Picture&quot;: &quot;summerbeach.png&quot;,
        ///      &quot;StartTime&quot;: &quot;2024-08-30T14:00:00&quot;,
        ///      &quot;EndTime&quot;: &quot;2024-08-30T18:00:00&quot;,
        ///      &quot;Location&quot;: &quot;Tel Aviv, Israel&quot;,
        ///      &quot;Description&quot;: &quot;Join us for a fun beach party with music, games, and food! Enjoy live DJ performances, beach volleyball, and a barbecue.\n\nLine-Up:\n14:00 - Opening Music and Welcome\n15:00 - Live DJ Performance\n16:00 - Beach Volleyball Tournament\n17 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eventData {
            get {
                return ResourceManager.GetString("eventData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Friends&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;John Doe&quot;,
        ///      &quot;ProfilePicture&quot;: &quot;https://example.com/johndoe.jpg&quot;,
        ///      &quot;Posts&quot;: [
        ///        &quot;Had a great day at the park!&quot;,
        ///        &quot;Loving the new coffee place in town.&quot;
        ///      ],
        ///      &quot;Friends&quot;: [
        ///        &quot;Jane Doe&quot;,
        ///        &quot;Mike Smith&quot;
        ///      ],
        ///      &quot;Pictures&quot;: [
        ///        &quot;https://example.com/photo1.jpg&quot;,
        ///        &quot;https://example.com/photo2.jpg&quot;
        ///      ],
        ///      &quot;IsCloseFriend&quot;: true
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Jane Doe&quot;,
        ///      &quot;ProfilePicture&quot;: &quot;https://example.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LikedPages&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;Tech Enthusiasts&quot;,
        ///      &quot;Category&quot;: &quot;Technology&quot;,
        ///      &quot;Posts&quot;: [
        ///        &quot;Exploring the latest in AI technology!&quot;,
        ///        &quot;Join us for a webinar on blockchain technology.&quot;,
        ///        &quot;New gadget review: The best smartphone of 2024.&quot;
        ///      ],
        ///      &quot;Picture&quot;: &quot;https://example.com/pictures/tech_enthusiasts.jpg&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Travel Lovers&quot;,
        ///      &quot;Category&quot;: &quot;Travel&quot;,
        ///      &quot;Posts&quot;: [
        ///        &quot;Top 10 destinations for 2024!&quot;,
        ///        &quot;Share your favorite [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Liked_Pages {
            get {
                return ResourceManager.GetString("Liked_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap summerbeach {
            get {
                object obj = ResourceManager.GetObject("summerbeach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tech {
            get {
                object obj = ResourceManager.GetObject("tech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
